remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"
title: CS-770 HCI
subtitle: "CS/Psych/EdPsych-770 Human-Computer Interaction"
author: Professor Zhao
description: "CS/Psych/EdPsych-770 Human-Computer Interaction, Fall 2022, Professor Zhao, University of Wisconsin--Madison"
search_enabled: true
# footer_content: "Copyright &copy 2020 Professor Bilge Mutlu"
header_pages:
  - index.md
  - schedule.md
  - syllabus.md

